force-app/main/default/objects/SystemSetting__mdt/SystemSetting__mdt.object-meta.xml
<CustomObject>
    <description>Centralized Custom Metadata Type to store settings to be used across the org.</description>
    <label>System Setting</label>
    <pluralLabel>System Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SystemSetting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The basic value. This will often be &quot;true&quot; or &quot;false&quot;, but you can store other things here, like API endpoints, etc.</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/TriggerService.cls
public without sharing abstract class TriggerService {

    /**
     * This class is in service of the ExampleAccountTriggerHandler.
     * Its purpose is to demonstrate how a Trigger action bypass might be implemented.
     * Arguably, this could live in the SystemSettingService, much like 'isFeatureOn'.
     * I think I like wrapping it in the TriggerService because when I'm in the TriggerHandler
     * wondering if the Trigger Action should be bypassed, my gut reaction was 'Better check the TriggerService'
     */
    public static Boolean isBypassEnabled(String triggerActionName){
        SystemSetting__mdt record = SystemSettingService.getByCategoryAndKey(SystemSettingService.CATEGORY_TRIGGER_ACTION_DISABLE, triggerActionName);
        return record==null ? false : record.Value__c.toLowerCase().trim() == 'true';
    }
}